name: Run `stack test` in all folders

on:
  push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Haskell
              uses: haskell/actions/setup@v2
              with:
                  ghc-version: "9.2.8"
                  enable-stack: true
                  stack-version: "latest"
            - name: Find and run Stack tests in all folders
              run: |
                for dir in */; do
                    if [ -f "$dir/stack.yaml" ]; then
                      echo "Running 'stack test' in $dir"
                      cd "$dir"
                      stack test
                      cd ..
                    fi
                done
                        